config/routes.rb
Rails.application.routes.draw do
  resources :proverbs
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/proverb.rb
class Proverb < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/proverbs_controller.rb
class ProverbsController < ApplicationController
  before_action :set_proverb, only: %i[ show edit update destroy ]

  # GET /proverbs or /proverbs.json
  def index
    @proverbs = Proverb.all
  end

  # GET /proverbs/1 or /proverbs/1.json
  def show
  end

  # GET /proverbs/new
  def new
    @proverb = Proverb.new
  end

  # GET /proverbs/1/edit
  def edit
  end

  # POST /proverbs or /proverbs.json
  def create
    @proverb = Proverb.new(proverb_params)

    respond_to do |format|
      if @proverb.save
        format.html { redirect_to proverb_url(@proverb), notice: "Proverb was successfully created." }
        format.json { render :show, status: :created, location: @proverb }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @proverb.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /proverbs/1 or /proverbs/1.json
  def update
    respond_to do |format|
      if @proverb.update(proverb_params)
        format.html { redirect_to proverb_url(@proverb), notice: "Proverb was successfully updated." }
        format.json { render :show, status: :ok, location: @proverb }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @proverb.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /proverbs/1 or /proverbs/1.json
  def destroy
    @proverb.destroy

    respond_to do |format|
      format.html { redirect_to proverbs_url, notice: "Proverb was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_proverb
      @proverb = Proverb.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def proverb_params
      params.require(:proverb).permit(:english, :translation, :active)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/proverbs_helper.rb
module ProverbsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Proverbs</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/proverbs/_form.html.erb
<%= form_with(model: proverb, local: true) do |form| %>
  <% if proverb.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(proverb.errors.count, "error") %> prohibited this proverb from being saved:</h2>

      <ul>
      <% proverb.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :english %>
    <%= form.text_field :english %>
  </div>

  <div class="field">
    <%= form.label :translation %>
    <%= form.text_field :translation %>
  </div>

  <div class="field">
    <%= form.label :active %>
    <%= form.check_box :active %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/proverbs/edit.html.erb
<h1>Editing Proverb</h1>

<%= render 'form', proverb: @proverb %>

<%= link_to 'Show', @proverb %> |
<%= link_to 'Back', proverbs_path %>

app/views/proverbs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Proverbs</h1>

<table>
  <thead>
    <tr>
      <th>English</th>
      <th>Translation</th>
      <th>Active</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @proverbs.each do |proverb| %>
      <tr>
        <td><%= proverb.english %></td>
        <td><%= proverb.translation %></td>
        <td><%= proverb.active %></td>
        <td><%= link_to 'Show', proverb %></td>
        <td><%= link_to 'Edit', edit_proverb_path(proverb) %></td>
        <td><%= link_to 'Destroy', proverb, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Proverb', new_proverb_path %>

app/views/proverbs/new.html.erb
<h1>New Proverb</h1>

<%= render 'form', proverb: @proverb %>

<%= link_to 'Back', proverbs_path %>

app/views/proverbs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>English:</strong>
  <%= @proverb.english %>
</p>

<p>
  <strong>Translation:</strong>
  <%= @proverb.translation %>
</p>

<p>
  <strong>Active:</strong>
  <%= @proverb.active %>
</p>

<%= link_to 'Edit', edit_proverb_path(@proverb) %> |
<%= link_to 'Back', proverbs_path %>